#! /bin/bash

profile="$1"
default_profile_name="default"
secrets_profile_name="secrets"
target_directory="$HOME"

process_file() {
    local profile_name="$1"
    local relative_filepath="$2"

    local absolute_source_path="`pwd`/$profile_name/$relative_filepath"
    local target_filepath="$target_directory/.$relative_filepath"
    local target_dirname=`dirname $target_filepath`

    if [ ! -d "$target_dirname" ]; then
        echo "creating directory [$target_dirname]"
        mkdir -p $target_dirname
    fi

    if [ -f "$target_filepath" ]; then
        if readlink "$target_filepath" > /dev/null; then
            echo "deleting existing link [$target_filepath]"
            rm $target_filepath
        else
            echo "WARNING: [$target_filepath] is present and is not a link"
            echo -n "do you want to replace it with a link? (y/n) "
            read c
            if [ "$c" = "y" ]; then
                rm $target_filepath
            else
                echo "ok, I wont touch it"
                return
            fi
        fi
    fi

    echo "linking $absolute_source_path to $target_filepath"
    ln -s $absolute_source_path $target_filepath
}

process_subdirectory() {
    local profile_name="$1"
    local directory="$2"

    if [ -z "$directory" ]; then
        echo "argument directory is blank" >&2
        exit 1
    fi

    echo "processing subdirectory $directory"

    local relative_path="$profile_name/$directory"

    for item in `/bin/ls -A $relative_path`; do
        local item_path="$relative_path/$item"
        echo "processing item [$item_path]"

        if [ -d "$item_path" ]; then
            echo "$item is a directory"
            process_subdirectory "$profile_name" "$directory/$item"
        fi

        if [ -f "$item_path" ]; then
            process_file $profile_name $directory/$item
        fi
    done
}

process_profile() {
    local profile_name="$1"

    if [ -z "$profile_name" ]; then
        echo "argument profile_name is blank" >&2
        exit 1
    fi

    echo "processing directory $profile_name"

    for item in `/bin/ls -A $profile_name`; do

        if [ -d "$profile_name/$item" ]; then
            echo "$item is a directory"
            process_subdirectory "$profile_name" "$item"
        fi

        if [ -f "$profile_name/$item" ]; then
            process_file $profile_name $item
        fi
    done
}

# -------

process_profile $default_profile_name
process_profile $secrets_profile_name
if [ ! -z "$profile" ]; then
    process_profile $profile
fi

