set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'editorconfig/editorconfig-vim'
Plugin 'vim-scripts/SyntaxRange'
Plugin 'vim-scripts/ingo-library'
Plugin 'altercation/vim-colors-solarized'
" Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'junegunn/fzf'
Plugin 'junegunn/gv.vim'
" Plugin 'scrooloose/nerdtree'
Plugin 'lokaltog/neoranger'
Plugin 'nathanaelkane/vim-indent-guides'
" Plugin 'majutsushi/tagbar'
" it sets a tons of mappings, its annoying
"Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'vim-airline'
" tools
Plugin 'tpope/vim-dadbod'
Plugin 'easymotion/vim-easymotion'

" IDE
Plugin 'neoclide/coc.nvim'
" Plugin 'scrooloose/syntastic'
" Plugin 'valloric/youcompleteme'
" Plugin 'ludovicchabant/vim-gutentags'
" Plugin 'shougo/deoplete.nvim'
" Plugin 'shougo/denite.nvim'
" it has a ts checker for syntastic
" Plugin 'quramy/tsuquyomi'

" syntax
Plugin 'sheerun/vim-polyglot'
Plugin 'leafgarland/typescript-vim'
Plugin 'pprovost/vim-ps1'
Plugin 'hashivim/vim-terraform'
Plugin 'tpope/vim-markdown'

" formatting
" Plugin 'Chiel92/vim-autoformat'


call vundle#end()            " required
filetype plugin indent on    " required

" jump to matching html/xml tags
" https://vi.stackexchange.com/a/784
runtime macros/matchit.vim

set laststatus=2
set t_Co=256

if &term =~ '256color'
    " disable Background Color Erase (BCE) so that color schemes
    " render properly when inside 256-color tmux and GNU screen.
    " see also http://sunaku.github.io/vim-256color-bce.html
    set t_ut=
endif

" copied from ddevault
set encoding=utf-8
set tabstop=4
set shiftwidth=4
set autoindent
set magic " unbreak vim's regex implementation

set number
set scrolloff=3
set sidescroll=3

set ruler
set cc=80
set nowrap

set ignorecase
set smartcase

set splitbelow
set hidden
set notimeout

" Search as you type, highlight results
set noincsearch " I find this annoying
set noshowmatch " I find this superannoying
set nohlsearch " I find this mildly annoying

" Don't litter swp files everywhere
set backupdir=~/.cache
set directory=~/.cache

set nofoldenable
set lazyredraw
set tags=./tags;
set printheader=\
" end ddevault copy

let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized

set clipboard+=unnamedplus

set cursorline
set nowrap
set noautoindent
set nosmartindent
set noexpandtab
set number

" tab as 4 spaces: https://stackoverflow.com/a/1878983/1407614
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab


" It does not work >.<
" https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" mappings
source ~/.vimrc.d/mappings.vim

" coc
source ~/.vimrc.d/coc.vim

" denite
" source ~/.vimrc.d/denite.vim

"Cursor settings:
"  1 -> blinking block
"  2 -> solid block
"  3 -> blinking underscore
"  4 -> solid underscore
"  5 -> blinking vertical bar
"  6 -> solid vertical bar

" tagbar
let g:tagbar_compact = 1
let g:tagbar_autofocus = 1
let g:tagbar_autoclose = 1

" wildignore (considered by ctrlp and, theoretically, gutentags. But gutentags seems to ignore it)
set wildignore+=*.so,*.swp,*.zip
set wildignore+=*/tmp/*,*/out/*,*/bin/*,*/obj/*,*/build/*,*/dist/*,*/node_modules/*,*/wwwroot/*,*/packages/*,*/.terraform/*

" deoplete
" let g:deoplete#enable_at_startup = 1

" syntastic
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" let g:syntastic_mode_map = { 'mode': 'passive','active_filetypes': [],'passive_filetypes': [] }
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 0
" let g:syntastic_check_on_wq = 0
" let g:syntastic_quiet_messages = { "type": "style" }
"" let g:tsuquyomi_disable_quickfix = 1
"" let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.
" let g:syntastic_typescript_checkers = ['tslint']
" let g:syntastic_javascript_checkers = ['standard']
" let g:syntastic_html_checkers = ['tidy']
"" https://vimawesome.com/plugin/youcompleteme
" let g:syntastic_java_checkers = []

"" youcompleteme ycm
" let g:ycm_key_detailed_diagnostics = ''
" let g:ycm_always_populate_location_list = 1


" gutentags
" let g:gutentags_enabled = 0
" let g:gutentags_ctags_tagfile = '.ctags'
" let g:gutentags_ctags_exclude = [ 'out', 'bin', 'obj', 'build', 'dist', 'node_modules', 'wwwroot', 'packages', '.terraform' ]

" editorconfig
" https://github.com/editorconfig/editorconfig-vim
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

" indent guides
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=darkgrey  ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=black  ctermbg=black
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_default_mapping = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_start_level = 2
let g:indent_guides_color_change_percent = 10

