# my .Xresources merging
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME $HOME/.Xresources

# make my binaries available
export PATH="$HOME/bin:$HOME/bin-utilities:$PATH"

# gnome keyring
# https://wiki.archlinux.org/index.php/GNOME/Keyring#Use_Without_Gnome
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# from lxsession
# https://wiki.archlinux.org/index.php/Polkit#Authentication_agents
# used by virt-manager to authenticate user via polkit
lxpolkit >/dev/null &

# clipboard does not work well in some applications, so I cannot use parcellite anymore
#parcellite >/dev/null &

# other stuffs
volumeicon >/dev/null &
slstatus >/dev/null &
cbatticon >/dev/null &
st -e screen >/dev/null &

# notification server, works with dbus and libnotify
dunst >/dev/null &

# bluetooth manager, works with bluez
blueman-applet >/dev/null &

# custom X11 keybindings
# I use this mainly to bind brightness control keys (see ~/.xbindkeysrc)
# it goes to background automatically, no need to append '&'
xbindkeys

# execute a '-locker' program (whatever it is) after '-time' minutes of user inactivity
xautolock -locker slock -time 5 -notifier 'notify-send -u critical -t 18 "locking in 20 seconds"' -notify 30 -detectsleep -corners 00-- >/dev/null &

# red gamma shifting, to save eyesight in the night xD
# https://wiki.archlinux.org/index.php/Redshift
# the first command of the following expression does not work anymore, I dunno why.
# it pops up an error saying that it cannot use geoclue
# 2019-04 - now it works again ¯\_(ツ)_/¯
redshift-gtk -l geoclue2 -t 6500:2750 &>/dev/null || redshift-gtk -t 6500:2750 -l 10.945856:43.719488 &>/dev/null &

# cleaning sxiv thumbnail cache
[[ -d $HOME/.cache/sxiv ]] && rm -rf $HOME/.cache/sxiv/*

# https://wiki.archlinux.org/index.php/Java#Non-reparenting_window_managers
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS="-Djdk.gtk.version=3 -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
# _JAVA_OPTIONS='-Dsun.java2d.opengl=true' <-- this option breaks intellij platform UI drawing! Do NOT add this.

# fix blank window in java applications
# https://blog.darknedgy.net/technology/2014/08/27/1/
wmname LG3D

# compton (composition manager)
#compton -bcCGf

# wallpaper
set-random-wallpaper.sh || feh -z --bg-fill ${HOME}/ent/wallpapers/*

# clean untagged docker images
docker-prune-notag-images.sh >~/.docker-prune.log 2>&1 &

# run dwm in loop, for easy reconfiguration
# to kill X11 use `killall xinit`
while true; do
	if [[ -x ~/bin/dwm ]]; then
		if [[ -r ~/bin/dwm-new ]]; then
			mv ~/bin/dwm-new ~/bin/dwm
		fi
		if [[ -r ~/bin/dwm_new ]]; then
             mv ~/bin/dwm_new ~/bin/dwm
        fi
        if [[ -r ~/bin/dwm_ ]]; then
             mv ~/bin/dwm_ ~/bin/dwm
        fi
	    ~/bin/dwm 2> $HOME/.dwm.log
	else
	    dwm 2> $HOME/.dwm.log
	fi
done
